### ISSUE TITLE
docker-compose service starting order

### ISSUE THREAD

**Issue by ramazansakin** [sivaprasadreddy/spring-boot-microservices-series#10]
Hi,

Generally, in lots of spring-boot microservices projects, also here, I see an order problem.
Before discovery service doesnt run, some other microservices gets an error "connection refused : service-registry - can not request on any server". But after a little time, generally most of services work and register successfully eureka.

Any idea?

**Comment by sivaprasadreddy** [comment]
We may need to use some tactics mentioned in https://docs.docker.com/compose/startup-order/ to control the order of container startup.

**Comment by ramazansakin** [comment]
Thnx @sivaprasadreddy
