### ISSUE TITLE
No Docker available for Apple M1 Chip

### ISSUE THREAD

**Issue by mdsardar** [sivaprasadreddy/spring-boot-microservices-series#11]
Hi All,

I'm trying to learn more about microservices by having this project as a reference. May I use this forum for clarification? Actually No stable docker version available for Apple M1 chip, so can I execute this project in my local development system, I mean without Docker ?

Thanks,
Mohammed Sardar

**Comment by ramazansakin** [comment]
Hi @mdsardar ,

Yes you can run all services without docker. As I see, there are both local and docker profiles in the app.
If any error occurs, I can help :)

**Comment by mdsardar** [comment]
Hi @**ramazansakin** ,

You rock and you are the best. 

Let me tell you,  I couldn't install Docker since a stable version was not available for the M1 chip. So, I'm trying to execute the services in the local development system.  I was unsure in which order to bootstrap the services, hence I decided to start the service registry, config server, oauth2 server, and then the other services.

When I run CatelogServiceApplication, InventoryServiceApplication is also getting the repetitive message as below. 

> 
> _2021-02-18 14:38:03.570  INFO [catalog-service,,,] 4534 --- [Mx8bDngWeRQ-922] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: **[localhost:5672]**
> 2021-02-18 14:38:08.662  WARN [catalog-service,,,] 4534 --- [Mx8bDngWeRQ-922] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
> 2021-02-18 14:38:08.668  INFO [catalog-service,,,] 4534 --- [Mx8bDngWeRQ-922] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4ffd2a3c: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
> 2021-02-18 14:38:08.672  INFO [catalog-service,,,] 4534 --- [Mx8bDngWeRQ-923] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:56_ 
> 

So from the above, I'm coming to know that catalog service is listening on the port **[localhost:5672]** to connect to RabbitMQ. From the guide written in this repo, I read that's for RabbitQ port. So do I need to set up this by installing any RabbitMQ? I can see from Spring Eureka that all the services are successfully registered to service registry. I need some help to progress from here. Could you please share your comments in this regards? Let me know if any other details needed please. 

I'm open to learning. 

Best,

**Comment by mdsardar** [comment]
@ramazansakin Currently, I'm reading this tutorial about [RabbitMQ](https://www.rabbitmq.com/tutorials/tutorial-one-spring-amqp.html). I'm thinking this needs installation.

**Comment by ramazansakin** [comment]
Firstly, your service start order is possible @mdsardar,

And if you have no docker installiation, you need to run rabbitMQ as local instance on ur machine and from that tutorial you can download and start the rabbitMQ with default configs.

**Comment by mdsardar** [comment]
@ramazansakin When I start the rabbitMQ instance getting the below message instead of what specified in the link. Any quick thoughts? 

>  
> sysphoton@CHMB127161 ~ % /usr/local/rabbitmq_server-3.8.12/sbin/rabbitmq-server ; exit;
> /usr/local/rabbitmq_server-3.8.12/sbin/rabbitmq-server: line 82: exec: erl: not found
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
>

**Comment by ramazansakin** [comment]
@mdsardar , As I see above error log, you have no Erlang installiation, right ?   >> erl: not found

**Comment by mdsardar** [comment]
> @mdsardar , As I see above error log, you have no Erlang installiation, right ? >> erl: not found

I've no much familiarity with Erlang in mac and I'm also new to Mac. Currently reading more about this topic.

**Comment by ramazansakin** [comment]
@mdsardar , rabbitMQ needs Erlang to work.

You can see that on rabbitMQ web site.
https://www.rabbitmq.com/which-erlang.html

**Comment by mdsardar** [comment]
> @mdsardar , rabbitMQ needs Erlang to work.
> 
> You can see that on rabbitMQ web site.
> https://www.rabbitmq.com/which-erlang.html

Could Erlang from Homebrew.

**Comment by mdsardar** [comment]
Shopping cart app microservices are up and responding now in my local. Yet, I'm curious to run those deploying into docker, but yet no stable docker available for M1 chip. 

Thank you all.
