### ISSUE TITLE
installation instructions only work on Windows

### ISSUE THREAD

**Issue by bmiddleb** [sivaprasadreddy/spring-boot-microservices-series#4]
It would be great if there were installation scripts for MacOS and/or *nix.

**Comment by jamesdube** [comment]
Worked well on my ubuntu unless there's something I'm missing

**Comment by karthikreddy521** [comment]
It all worked fine for me in Mac.

**Comment by sivaprasadreddy** [comment]
> It would be great if there were installation scripts for MacOS and/or *nix.

Are you facing any specific issue on Linux/MacOS?

**Comment by sivaprasadreddy** [comment]
Closing this issue, if you are still facing issues on Mac or Linux please re-open.
